version: "3.9"

services:
# ======================
# Postgres кластер
# =====================
  postgres-master:
    image: postgres:15
    container_name: clickstream-postgres-master
    hostname: postgres-master
    environment:
      POSTGRES_DB: clickstream
      POSTGRES_USER: clickstream
      POSTGRES_PASSWORD: clickstream
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
      - ./postgres/master.conf:/etc/postgresql/master.conf:ro
      - ./postgres/init-master.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./postgres/setup-hba.sh:/docker-entrypoint-initdb.d/02-hba.sh:ro
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clickstream"]
      interval: 10s

  postgres-replica:
    image: postgres:15
    container_name: clickstream-postgres-replica
    hostname: postgres-replica
    volumes:
      - postgres_replica_data:/var/lib/postgres/data
      - ./postgres/replica.conf:/etc/postgres/postgresql.conf
      - ./postgres/setup-replica.sh:/setup-replica.sh:ro
    entrypoint: ["/bin/bash", "/setup-replica.sh"]
    depends_on:
      postgres-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clickstream"]
      interval: 10s

  postgres:
    image: edoburu/pgbouncer:latest
    container_name: clickstream-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini:ro
      - ./pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt:ro
    depends_on:
      postgres-master:
        condition: service_healthy
      postgres-replica:
        condition: service_healthy

# ======================
# RabbitMQ кластер
# =====================
  rabbitmq1:
    image: rabbitmq:3.13-management
    container_name: clickstream-rabbitmq1
    hostname: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secretcookie'
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq1_data:/var/lib/rabbitmq
      - ./rabbitmq/docker-entrypoint.sh:/docker-entrypoint.sh:ro

  rabbitmq2:
    image: rabbitmq:3.13-management
    container_name: clickstream-rabbitmq2
    hostname: rabbitmq2
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secretcookie'
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq2_data:/var/lib/rabbitmq
      - ./rabbitmq/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    depends_on:
      - rabbitmq1

  rabbitmq3:
    image: rabbitmq:3.13-management
    container_name: clickstream-rabbitmq3
    hostname: rabbitmq3
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secretcookie'
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq3_data:/var/lib/rabbitmq
      - ./rabbitmq/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    depends_on:
      - rabbitmq1

  rabbitmq-haproxy:
    image: haproxy:2.9
    container_name: clickstream-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - ./haproxy/rabbitmq.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3

  # ======================
  # API / Consumer / Producer / Tracker / Event Generator
  # ======================
  api:
    build: ./api
    container_name: clickstream-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started


  consumer:
    build: ./consumer
    container_name: clickstream-consumer
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
      rabbitmq-haproxy:
        condition: service_started
    restart: always 

  producer:
    build: ./producer
    container_name: clickstream-producer
    env_file:
      - .env
    depends_on:
      rabbitmq-haproxy:
        condition: service_started
    restart: always 
    
  event-generator:
    build: ./event_generator
    container_name: clickstream-generator
    env_file:
      - .env
    volumes:
      - ./data:/data
    depends_on:
      api:
        condition: service_started
      consumer:
        condition: service_started
      postgres:
        condition: service_started

  tracker:
    build: ./tracker
    container_name: clickstream-tracker
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_USER=clickstream
      - DB_PASSWORD=clickstream
      - DB_NAME=clickstream
    depends_on:
      - postgres

  # ======================
  # ClickHouse
  # ======================
  clickhouse:
    image: clickhouse/clickhouse-server:23.9
    container_name: clickstream-clickhouse
    ports:
      - "18123:8123"
      - "19000:9000"
      - "9363:9363"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-init:/docker-entrypoint-initdb.d  # SQL для инициализации
      - ./clickhouse-config/prometheus.xml:/etc/clickhouse-server/config.d/prometheus.xml
    environment:
      CLICKHOUSE_DB: clickstream
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # ======================
  # Airflow
  # ======================
  airflow:
    build: ./airflow
    container_name: clickstream-airflow
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: "${AIRFLOW_FERNET_KEY:-$(python3 -c 'from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())')}"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://clickstream:clickstream@postgres:5432/clickstream_write
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__METRICS__STATS_D_ON: "true"
      AIRFLOW__METRICS__PROMETHEUS: "true"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/etl:/opt/airflow/etl
      - ./airflow/scripts:/opt/airflow/scripts
      - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg:ro
      - ./airflow/docker-entrypoint.sh:/entrypoint.sh:ro
    ports:
      - "8082:8080"
      - "9191:9191"

    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com || true
        airflow webserver & airflow scheduler
      "




    healthcheck:
      test: ["CMD-SHELL", "airflow db check"]
      interval: 10s
      retries: 5

    depends_on:
      postgres:
        condition: service_started




  # ======================
  # Prometheus
  # ======================
  prometheus:
    image: prom/prometheus:latest
    container_name: clickstream-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - clickhouse

  # ======================
  # Grafana
  # ======================
  grafana:
    image: grafana/grafana:latest
    container_name: clickstream-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DEFAULT_APP_MODE=development
      - GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  tests:
    build: .
    profiles: ["tests"]
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: clickstream
      POSTGRES_PASSWORD: clickstream
      POSTGRES_DB: clickstream_write
    volumes:
      - .:/app
    command: ["python", "run_tests.py"]
   

volumes:
  postgres_master_data:
  postgres_replica_data:
  clickhouse_data:
  grafana_data:
  rabbitmq1_data:
  rabbitmq2_data:
  rabbitmq3_data: