apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    isDefault: false

  - name: ClickHouse
    type: "vertamedia-clickhouse-datasource"
    uid: clickhouse
    access: proxy
    url: http://clickstream-clickhouse:8123
    database: clickstream
    user: default
    password: ""
    isDefault: true
    jsonData:
      timeInterval: "1s"
