{
 "title": "analytical dashboard",
 "time": { "from": "2026-01-07T08:12:09.000Z", "to": "2026-01-07T08:17:04.000Z" },
 "panels": [
  {
   "title": "DAU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Pages Devices1', user=1 */\nWITH\r\n    (\r\n        SELECT countDistinct(user_id) AS dau\r\n        FROM clickstream.events_cleansed\r\n        WHERE created_at >= today()\r\n    ) AS v\r\nSELECT\r\n    now() - INTERVAL number*5 SECOND AS time,\r\n    v AS value\r\nFROM numbers(60)  \nORDER BY time",
     "query": "WITH\r\n    (\r\n        SELECT countDistinct(user_id) AS dau\r\n        FROM clickstream.events_cleansed\r\n        WHERE created_at >= today()\r\n    ) AS v\r\nSELECT\r\n    now() - INTERVAL number*5 SECOND AS time,\r\n    v AS value\r\nFROM numbers(60)  -- 60 точек по 5 секунд = 5 минут\r\nORDER BY time\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "MAU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Pages Devices1', user=1 */\nWITH\r\n    (\r\n        SELECT countDistinct(user_id) AS mau\r\n        FROM clickstream.events_cleansed\r\n        WHERE created_at >= now() - INTERVAL 30 DAY\r\n    ) AS v\r\nSELECT\r\n    now() - INTERVAL number*5 SECOND AS time,\r\n    v AS value\r\nFROM numbers(60)  \nORDER BY time",
     "query": "WITH\r\n    (\r\n        SELECT countDistinct(user_id) AS mau\r\n        FROM clickstream.events_cleansed\r\n        WHERE created_at >= now() - INTERVAL 30 DAY\r\n    ) AS v\r\nSELECT\r\n    now() - INTERVAL number*5 SECOND AS time,\r\n    v AS value\r\nFROM numbers(60)  -- 60 точек по 5 секунд = 5 минут графика\r\nORDER BY time\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "WAU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Pages Devices1', user=1 */\nWITH\r\n    (\r\n        SELECT countDistinct(user_id) AS wau\r\n        FROM clickstream.events_cleansed\r\n        WHERE created_at >= now() - INTERVAL 7 DAY\r\n    ) AS v\r\nSELECT\r\n    now() - INTERVAL number*5 SECOND AS time,\r\n    v AS value\r\nFROM numbers(60)  \nORDER BY time",
     "query": "WITH\r\n    (\r\n        SELECT countDistinct(user_id) AS wau\r\n        FROM clickstream.events_cleansed\r\n        WHERE created_at >= now() - INTERVAL 7 DAY\r\n    ) AS v\r\nSELECT\r\n    now() - INTERVAL number*5 SECOND AS time,\r\n    v AS value\r\nFROM numbers(60)  -- 60 точек по 5 секунд\r\nORDER BY time\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "clicks/views",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "contextWindowSize": "10",
     "dateTimeType": "DATETIME",
     "formattedQuery": "/* grafana dashboard='Pages Devices1', user=1 */\nSELECT\r\n    toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time,\r\n    countIf(type = 'click' and element_id = '#btn') AS btn_clicks\r\nFROM clickstream.events_cleansed\r\nWHERE created_at >= now() - INTERVAL 24 hours \r\nGROUP BY time\r\nORDER BY time",
     "query": "SELECT\r\n    toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time,\r\n    countIf(type = 'click' and element_id = '#btn') AS btn_clicks\r\nFROM clickstream.events_cleansed\r\nWHERE created_at >= now() - INTERVAL 24 hours \r\nGROUP BY time\r\nORDER BY time\r\n",
     "round": "0s"
    },
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Pages Devices1', user=1 */\nSELECT\r\n    toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time,\r\n    countIf(type = 'view') AS views\r\nFROM clickstream.events_cleansed\r\nWHERE created_at >= now() - INTERVAL 24 hours \r\nGROUP BY time\r\nORDER BY time",
     "query": "SELECT\r\n    toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time,\r\n    countIf(type = 'view') AS views\r\nFROM clickstream.events_cleansed\r\nWHERE created_at >= now() - INTERVAL 24 hours \r\nGROUP BY time\r\nORDER BY time\r\n",
     "round": "0s"
    },
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Pages Devices1', user=1 */\nSELECT\r\n    toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time,\r\n    countIf(type = 'click' and element_id = '#link') AS link_clicks\r\nFROM clickstream.events_cleansed\r\nWHERE created_at >= now() - INTERVAL 24 hours \r\nGROUP BY time\r\nORDER BY time",
     "query": "SELECT\r\n    toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time,\r\n    countIf(type = 'click' and element_id = '#link') AS link_clicks\r\nFROM clickstream.events_cleansed\r\nWHERE created_at >= now() - INTERVAL 24 hours \r\nGROUP BY time\r\nORDER BY time\r\n",
     "round": "0s"
    },
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Pages Devices1', user=1 */\nSELECT\r\n    toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time,\r\n    countIf(type = 'click' and element_id = '#submit') AS submit_clicks\r\nFROM clickstream.events_cleansed\r\nWHERE created_at >= now() - INTERVAL 24 hours \r\nGROUP BY time\r\nORDER BY time",
     "query": "SELECT\r\n    toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time,\r\n    countIf(type = 'click' and element_id = '#submit') AS submit_clicks\r\nFROM clickstream.events_cleansed\r\nWHERE created_at >= now() - INTERVAL 24 hours \r\nGROUP BY time\r\nORDER BY time\r\n",
     "round": "0s"
    },
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Pages Devices1', user=1 */\nSELECT\r\n    toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time,\r\n    countIf(type = 'click' ) AS sum_clicks\r\nFROM clickstream.events_cleansed\r\nWHERE created_at >= now() - INTERVAL 24 hours \r\nGROUP BY time\r\nORDER BY time",
     "query": "SELECT\r\n    toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time,\r\n    countIf(type = 'click' ) AS sum_clicks\r\nFROM clickstream.events_cleansed\r\nWHERE created_at >= now() - INTERVAL 24 hours \r\nGROUP BY time\r\nORDER BY time\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "clicks/views%",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Pages Devices1', user=1 */\nSELECT\r\n    toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time,\r\n    (countIf(event_title = 'button_click') + countIf(event_title = 'button'))/\r\n    countIf(event_title = 'page_view') * 100 AS percent\r\nFROM clickstream.events_cleansed\r\nWHERE created_at >= now() - INTERVAL 24 hours \r\nGROUP BY time\r\nORDER BY time",
     "query": "SELECT\r\n    toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time,\r\n    (countIf(event_title = 'button_click') + countIf(event_title = 'button'))/\r\n    countIf(event_title = 'page_view') * 100 AS percent\r\nFROM clickstream.events_cleansed\r\nWHERE created_at >= now() - INTERVAL 24 hours \r\nGROUP BY time\r\nORDER BY time\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Button Clicks by Element",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='User Activity Extended', user=1 */\nSELECT element_id, count(*) AS clicks FROM clickstream.events_cleansed WHERE  created_at >= now() - INTERVAL 30 DAY AND created_at <= now() GROUP BY element_id ORDER BY clicks DESC LIMIT 10",
     "query": "SELECT element_id, count(*) AS clicks FROM clickstream.events_cleansed WHERE  created_at >= now() - INTERVAL 30 DAY AND created_at <= now() GROUP BY element_id ORDER BY clicks DESC LIMIT 10",
     "rawSql": "SELECT element_id, count(*) AS clicks FROM clickstream.events_cleansed WHERE event_title='button_click' AND created_at >= now() - INTERVAL 30 DAY AND created_at <= now() GROUP BY element_id ORDER BY clicks DESC LIMIT 10",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Avg session duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Pages Devices1', user=1 */\nSELECT\r\n    toStartOfInterval(session_start, INTERVAL 10 SECOND) AS time,\r\n    avg(session_duration) AS avg_session_duration_seconds\r\nFROM\r\n(\r\n    SELECT\r\n        session_id,\r\n        min(created_at) AS session_start,\r\n        max(created_at) AS session_end,\r\n        dateDiff('second', min(created_at), max(created_at)) AS session_duration\r\n    FROM clickstream.events_cleansed\r\n    WHERE created_at >= now() - INTERVAL 24 hour\r\n    GROUP BY session_id\r\n)\r\nGROUP BY time\r\nORDER BY time",
     "query": "SELECT\r\n    toStartOfInterval(session_start, INTERVAL 10 SECOND) AS time,\r\n    avg(session_duration) AS avg_session_duration_seconds\r\nFROM\r\n(\r\n    SELECT\r\n        session_id,\r\n        min(created_at) AS session_start,\r\n        max(created_at) AS session_end,\r\n        dateDiff('second', min(created_at), max(created_at)) AS session_duration\r\n    FROM clickstream.events_cleansed\r\n    WHERE created_at >= now() - INTERVAL 24 hour\r\n    GROUP BY session_id\r\n)\r\nGROUP BY time\r\nORDER BY time\r\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "device types",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Pages Devices1', user=1 */\nSELECT toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time, device_type, count() AS events_count FROM clickstream.events_cleansed WHERE created_at >= now() - INTERVAL 24 hour GROUP BY time, device_type ORDER BY time, device_type",
     "query": "SELECT toStartOfInterval(created_at, INTERVAL 10 SECOND) AS time, device_type, count() AS events_count FROM clickstream.events_cleansed WHERE created_at >= now() - INTERVAL 24 hour GROUP BY time, device_type ORDER BY time, device_type",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Top 10 Pages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 32 },
   "targets": [
    {
     "contextWindowSize": "10",
     "formattedQuery": "/* grafana dashboard='Pages Devices1', user=1 */\nSELECT url, count(*) AS views FROM clickstream.events_cleansed WHERE event_title='page_view' AND created_at >= now() - INTERVAL 30 DAY AND created_at <= now() GROUP BY url ORDER BY views DESC LIMIT 10",
     "query": "SELECT url, count(*) AS views FROM clickstream.events_cleansed WHERE event_title='page_view' AND created_at >= now() - INTERVAL 30 DAY AND created_at <= now() GROUP BY url ORDER BY views DESC LIMIT 10",
     "rawSql": "SELECT url, count(*) AS views FROM clickstream.events_cleansed WHERE event_title='page_view' AND created_at >= now() - INTERVAL 30 DAY AND created_at <= now() GROUP BY url ORDER BY views DESC LIMIT 10",
     "round": "0s"
    }
   ]
  }
 ]
}