{
 "title": "ClickHouse System Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ClickHouseProfileEvents_Query", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ClickHouseProfileEvents_SelectQueryTimeMicroseconds",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Виртуальное время CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ClickHouseProfileEvents_OSCPUVirtualTimeMicroseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU пользовательский",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_OSUserTimeNormalized",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU системный",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_OSSystemTimeNormalized",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "ClickHouseProfileEvents_OSIOWaitMicroseconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Объём данных MergeTree",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_TotalBytesOfMergeTreeTables",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кол-во строк MergeTree",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_TotalRowsOfMergeTreeTables",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сеть вход/выход",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_NetworkReceiveBytes_eth0",
     "legendFormat": "__auto"
    },
    {
     "expr": "ClickHouseAsyncMetrics_NetworkSendBytes_eth0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MemoryTracking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}