{
 "title": "rabbit monitor",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Общее число операций",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_channel_process_reductions_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS line",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(rabbitmq_global_messages_received_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(rabbitmq_global_messages_received_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expression": "$A / 1024 / 1024", "type": "math" }
   ]
  },
  {
   "title": "disk_space_available (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expression": "$A / 1024 / 1024 / 1024", "type": "math" }
   ]
  },
  {
   "title": "Network incoming (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expression": "$A/1024/1024", "type": "math" }
   ]
  },
  {
   "title": "uptime (s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_erlang_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network outcoming (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expression": "$A/1024/1024", "type": "math" }
   ]
  },
  {
   "title": "connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "rabbitmq_connections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rabbitmq_alarms_memory_used_watermark",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}