# МОНИТОРИНГ: метрики RPS/latency
shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = all
pg_stat_statements.max = 10000

# Latency: логи запросов > 250ms
log_min_duration_statement = 250
log_checkpoints = on

# Статистика БД (RPS)
track_activity_query_size = 4096
track_counts = on
track_io_timing = on

# Сетевые метрики
log_connections = on
log_disconnections = on

# Файл: postgres/master.conf
listen_addresses = '*'
wal_level = replica
max_wal_senders = 10
wal_keep_size = 64
hot_standby = on
