# Разрешаем репликацию любому хосту
host replication replicator 0.0.0.0/0 md5

# Разрешаем все TCP-подключения (для удобства)
host all all 0.0.0.0/0 md5

# Разрешаем локальные подключения
local   all             all                                     trust
